# -*- coding: utf-8 -*-
"""python_practice_loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zUBqcJEhyPyoKdODwpYRr6Ng8tU_HftQ

# I. range.

1. (4 бали) Створіть обʼєкт типу range, який буде містити послідовність цілих чисел від 0 до 9 включно. Виведіть його довжину (кількість значень).
"""

len(range(10))

"""2. (5 балів) Створіть обʼєкт типу range, який буде містити послідовність цілих чисел (16, 13, 10, 7, 4, 1, -2, -5)"""

x_range = range(16,-6,-3)
for i in x_range:
  print(i)

"""3. (4 бали) Створіть змінну зі значенням цілого типу. Перевірте, чи вона належить проміжку від 49 до 100 включно. Як ви гадаєте, для чого використовуються range?"""

int_a = 55
int_b = 30
if int_b in range(49,101):
  print("Included")
else:
  print("Not included")

"""**місце для відповіді*

Range використовується для створення об'єкта, який пердсатовляє собою ціло чисельний ряд.

# II. Comprehensions.

4. (6 балів) Створіть множину (set), використовуючи range та set comprehension.
"""

range_set = {i for i in range(10)}
range_set

"""5. (8 балів) Створіть словник, використовуючи dict comprehension, що містить if else. Коли слід використовувати comprehensions, а коли їх слід уникати?"""

my_dict = {x: 'Even' if x%2==0 else 'Odd' for x in range(1,5)}
my_dict

"""**місце для відповіді*

6. (7 балів) Створіть список з рядками та запишіть його у змінну. Створіть ще один список на основі попереднього, де кожен рядок буде містити тільки три перших заглавних символи. Наприклад: ['hello', 'i', 'dont', 'care'] -> ['HEL', 'I', 'DON', 'CAR']
"""

phrase_list = ['Hello','Don`t','Like']
capital_list = [s[:3].upper() for s in phrase_list]
capital_list

"""# III. Цикли.

7. (6 балів) Продемонструйте роботу циклу while. Чи можна використовувати в умові циклу булеві значення? Чому?
"""

i=0
while i in range(5):
  print("Hello", {i})
  i+=1

"""8. (8 балів) Напишіть програму, яка виведе на екран непарні числа в діапазоні від 0 до 20 включно."""

for i in range(21):
  if i%2==1:
    print(i)

"""9. (7 балів) Створіть список з елементами булевого типу або None. Використовуючи цикли, отримайте в результаті список з кортежами, де перший елемент кортежу - індекс(ціле число), а другий елемент - відповідне значення з першого списку.

Наприклад, [True, True, None, False] -> [(0, True), (1, True), (2, None), (3, False)]
"""

boolean_list = [True, False, None, True, False, None]
final_boolean_list = []

for index, value in enumerate(boolean_list):
    final_boolean_list.append((index, value))

print(final_boolean_list)

"""10. (10 балів) Створіть словник, де ключі - назви книжок, а значення - їхня кількість у наявності в Вашій міні-бібліотеці. Бібліотека має містити щонайменше 6 книжок (6 пар значень у словнику) і щонайбільше 10 (пар значень). Використовуючи цикли, оновіть словник (не створюйте новий) так, щоби кількість книг у наявності збільшилося на 5 кожної книги. Наприклад,
{'It': 3, 'Fault stars': 10, 'Bible': 17, 'Psychological romance': 4, 'Harry Potter': 13} -> {'It': 8, 'Fault stars': 15, 'Bible': 22, 'Psychological romance': 9, 'Harry Potter': 18}
"""

book_dict = {'It': 3, 'Fault stars': 10, 'Bible': 17, 'Psychological romance': 4, 'Harry Potter': 13}

for book in book_dict:
    book_dict[book] += 5

print(book_dict)

"""11. (15 балів) Визначте цілочислену змінну n, що належить проміжку від 4 до 10 включно. Використовуючи цикли, виведіть в консоль наступний патерн.

#
##
###
####

... #*n

"""

n=5
for i in range(n+1):
  stars = '*'*i
  print(stars)

"""12. (20 балів) Гра "Нумо вгадай".
Розробіть просту гру, де користувач має вгадати випадкове число від 1 до 100. Для генерації випадкового числа використовуйте функцію random.randint(a, b) (тут a та b включно). Для отримання числа з консолі використовуйте функцію input(), результат якої обовʼязково явно приведіть до типу int.

Підказка: використовуйте цикл while та умови if-else, щоб повідомити користувачу піказки (напр. "Більше", "Менше") поки користувач не вгадає. По завершенню виведіть кількість спроб, які знадобилися для вгадування.

"""

import random
random_number = random.randint(1,100)
attempts = 0

print('Guess the number between 1 and 100')

while True:

  user_input = input()
  user_input = int(user_input)
  attempts += 1

  if user_input > random_number:
    print('Lower: ')
  elif user_input < random_number:
    print('Higher: ')
  else:
    print('Victory!')
    print('Attempts:',attempts)
    break

"""# Вітаю! Ви велика(ий) молодець, що впоралась(вся). Похваліть себе та побалуйте чимось приємним. Я Вами пишаюся."""